export const employerPartners = [
  {
    id: '1',
    name: 'Chipotle',
    mprEnabled: true,
    platformNavEnabled: true,
    products: ['Grow', 'TR Global', 'Navigator'],
  },
  {
    id: '2',
    name: 'Walmart',
    mprEnabled: true,
    platformNavEnabled: false,
    products: ['Grow', 'TR Global', 'Navigator', 'Academy'],
  },
  {
    id: '3',
    name: 'Amazon',
    mprEnabled: true,
    platformNavEnabled: true,
    products: ['TR Global', 'Navigator', 'Academy'],
  },
  {
    id: '4',
    name: 'Target',
    mprEnabled: false,
    platformNavEnabled: true,
    products: ['Grow', 'Academy'],
  },
  {
    id: '5',
    name: "McDonald's",
    mprEnabled: false,
    platformNavEnabled: false,
    products: ['Grow'],
  },
  {
    id: '6',
    name: 'Starbucks',
    mprEnabled: true,
    platformNavEnabled: true,
    products: ['Grow', 'TR Global'],
  },
  {
    id: '7',
    name: 'Home Depot',
    mprEnabled: false,
    platformNavEnabled: true,
    products: ['Navigator', 'Academy'],
  },
  {
    id: '8',
    name: 'FedEx',
    mprEnabled: true,
    platformNavEnabled: false,
    products: ['Grow', 'Navigator'],
  },
  {
    id: '9',
    name: 'UPS',
    mprEnabled: false,
    platformNavEnabled: false,
    products: ['TR Global'],
  },
  {
    id: '10',
    name: 'Disney',
    mprEnabled: true,
    platformNavEnabled: true,
    products: ['Grow', 'TR Global', 'Navigator', 'Academy'],
  },
  {
    id: '11',
    name: "Lowe's",
    mprEnabled: false,
    platformNavEnabled: true,
    products: ['Grow', 'Academy'],
  },
  {
    id: '12',
    name: 'Kroger',
    mprEnabled: true,
    platformNavEnabled: false,
    products: ['TR Global', 'Academy'],
  },
]
